CREATE DATABASE IF NOT EXISTS HOSPITAL;

CREATE TABLE IF NOT EXISTS HOSPITAL.DOCTOR(
    DOCTOR_ID VARCHAR(10) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    CONTACT_NUMBER VARCHAR(50) NOT NULL,
    SPECIALIZATION VARCHAR(50) NOT NULL,
    PRIMARY KEY(DOCTOR_ID)
);

CREATE TABLE IF NOT EXISTS HOSPITAL.PATIENT(
    PATIENT_ID VARCHAR(10) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DOB VARCHAR(20) NOT NULL,
    SEX VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(50) NOT NULL,
    BLOOD VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPITAL.MED_CASE(
    CASE_ID VARCHAR(50) PRIMARY KEY NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    LABWORK BOOLEAN NOT NULL,
    PRESCRIPTION BOOLEAN NOT NULL,
    PATIENT_ID VARCHAR(50) NOT NULL,
    DOCTOR_ID VARCHAR(50) NOT NULL,
    FOREIGN KEY(PATIENT_ID) REFERENCES HOSPITAL.PATIENT(PATIENT_ID),
    FOREIGN KEY(DOCTOR_ID) REFERENCES HOSPITAL.DOCTOR(DOCTOR_ID)
);

SELECT COUNT(*) FROM hospital.doctor;
SELECT COUNT(*) FROM hospital.med_case;
SELECT COUNT(*) FROM hospital.patient;
